### ISSUE TITLE
Pins for Arduino mega?

### ISSUE THREAD

**Issue by bendeguztanczos** [mkovero/7226ctrl#13]
Hi all! Anyone try it on Arduino mega? I thought I make a full smd board with atmega2560. Anyone have pins.h for arduino mega? And how well it is run on mega or i need teensy?

**Comment by mkovero** [comment]
I used to develop this on arduino mega, but unfortunately there are few quite heavy float calculation nowadays and I'm afraid that mega wont perform enough to handle it not to mention it would not have enough available memory to even try to run the code. Teensy 3.5 is highly recommended.
