### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by ikulic** [mkovero/7226ctrl#5]
Hi,can you upload your necessary library folder for that code? I have problem with compiling with last version of Arduino IDE.

**Comment by mkovero** [comment]
Hi, Yes I have to check best way to include libraries, external dependencies are as follows:
https://github.com/prampec/arduino-softtimer for softtimer.h
https://github.com/olikraus/u8g2 for U8g2lib.h
http://ryandowning.net/AutoPID/ for AutoPID.h

**Comment by ikulic** [comment]
Now it is working,thank you. If you need some help with this project,you can contact me. Now I am working on two 722.6 transmision,I just waiting for pcb to manufacture. I will put that transmission on om606 and we will see.
